### ISSUE TITLE
Intel Dual Band Wireless-AC 8265 working ?

### ISSUE THREAD

**Issue by arno608rw** [kk1987/T480s-hackintosh#3]
original card Intel Dual Band Wireless-AC 8265 working ?

**Comment by kk1987** [comment]
no

**Comment by arno608rw** [comment]
This OK?
https://www.ebay.com/itm/New-Broadcom-BCM94352Z-M-2-NGFF-802-11AC-867Mbps-BT-4-0-DW1560-f-Mac-Hackintosh/252319175707

**Comment by kk1987** [comment]
Yeah that should work
