### ISSUE TITLE
Thunderbolt:	No drivers are loaded.

### ISSUE THREAD

**Issue by philffm** [kk1987/T480s-hackintosh#5]
Hi, thank you for this repository ! Everything went fine so far. 
However, I am still struggling with my TB3 devices (HP Omen Accelerator) - it starts spinning, but is not detected by macOS.

In System Information it says: "Thunderbolt: No drivers are loaded."

Tried with both settings: BIOS assist enabled/disabled

Do you have any idea, how to solve this :)?

Best, Phil

<img width="402" alt="screenshot 2019-02-15 at 15 19 08" src="https://user-images.githubusercontent.com/6079545/52862362-66d87400-3135-11e9-8208-225d9457d78d.png">

**UPDATE 1:** 

Uh, damn - just read, that Thunderbolt is still considered as a "weak" spot in hackintoshing. Thought, I found  the perfect replacement for my MacBook (just feels fragile and I want to escape the service-dependency and potential high repair costs towards apple - but however already have this eGPU setup, so I needed a capable device with "working" TB3 :D). Seems, I need to find another solution to use my ThinkPad with monitors - at least it has all the ports and still I can use the GPU in Windows for now. 

**UPDATE 2:** 
Partly success: When booting up with TB3 device attached (HP Omen Accelerator), the following things are detected / working (hot-plug does not work - neither does GPU (RX580) spin-up and work) :

- Charging 
- USB - Ports (HP Omen)
- Internal SSD (HP Omen)
- Ethernet port (HP Omen)

Still, if you have any advice on where to start and whether it is worth to continue at all, let me know :) (Would have a look at: https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/)

**UPDATE 3:** 
Hotplug works now  - thanks to the SSDT-TB3.aml from https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/ (except after sleep - after sleep, only PD keeps working) 

However, the eGPU is visible in the IOreg explorer (see screenshot) and even the "eGPU" icon in the top bar shows up for a few seconds - but without detecting a GPU . 

<img width="1287" alt="screenshot 2019-02-15 at 15 17 06" src="https://user-images.githubusercontent.com/6079545/52862371-6cce5500-3135-11e9-8fda-c73667208428.png">

**Comment by philffm** [comment]
Put the thread here for further discussion: 

https://www.tonymacx86.com/threads/success-macos-10-14-on-thinkpad-t480s.261318/post-1909488

**Comment by Mifaxav** [comment]
i have a usb type c dock attacked to my T480 hackintosh NOT a T480S. i can output to 2 displays at the same time. does this mean my thuderbolt is working?
