### ISSUE TITLE
What kind of Wifi Card did you use?

### ISSUE THREAD

**Issue by nemonein** [kk1987/T480s-hackintosh#6]
Hello.
Thank you for your sharing the info about Thinkpad and Hackintosh.
I was wondering how you could replace wifi module, with BCM94352Z.
```
BCM94352Z M.2 WiFi + BT (card is E-key while mobo slot is A-key; mechanically modified with knife/file to fit)
```
Doesn't Thinkpad 480s have whitelist issue?
I would like to know [something like this card](https://www.aliexpress.com/item/BCM94352Z-802-11ac-NGFF-M2-Dual-band-2x2-AC-BT4-0-867Mbps-Wireless-Card/32487923741.html?spm=2114.search0104.3.2.4c2955d3aiEyUQ&ws_ab_test=searchweb0_0,searchweb201602_9_10065_10068_319_10059_10884_317_10887_10696_321_322_10084_453_10083_454_10103_10618_10307_10712_537_536_10713_10902,searchweb201603_59,ppcSwitch_0&algo_expid=9f6c95dc-f927-4fe6-b93d-305e3e451007-0&algo_pvid=9f6c95dc-f927-4fe6-b93d-305e3e451007&transAbTest=ae803_3) can be used in Thinkpad T480s.

Thank you for reading.

**Comment by kk1987** [comment]
hi @nemonein 

AFAIK the T480s (and in fact all recent ThinkPads) doesn't have a WiFi whitelist. The card in your link should work as-is (since it is A+E keyed)

**Comment by nemonein** [comment]
Thank you very much!
