### ISSUE TITLE
How is Brightness shortcut key configured 

### ISSUE THREAD

**Issue by vumvo** [kk1987/T480s-hackintosh#9]
Can you show me where the brightness shortcut keys configured in your clover? I have mine with brightness shortcut keys not working.
Thanks for your help.

**Comment by kk1987** [comment]
see ACPI/dsl/SSDT-KBD.dsl

**Comment by vumvo** [comment]
It's worked. Thanks so much.

**Comment by ghost** [comment]
What do I do with *.dsl files? 

I've tried compiling (saving as *.aml) [this](https://github.com/acidanthera/VoodooPS2/blob/master/Docs/ACPI/SSDT-Thinkpad_Clickpad.dsl) and putting the resulting aml file into EFI/CLOVER/ACPI/patched but I still have an issue with the trackpad (scrolling triggers middle click)
